### PR TITLE
Add the read for the 0 register of the (RA|0) case from the ISA.

### PR DESCRIPTION
**Pull request by Rot127**

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@Rot127 have you checked these changes against the mainstream QEMU?

**Comment by XVilka** [comment]
@wargio take a look please

**Comment by Rot127** [comment]
@XVilka 
> have you checked these changes against the mainstream QEMU?

Well, QEMU checks if the `rA` variable is `0` and then does operations as if it was never there. The ISA though explicitly states, that `0` is used. LLVM implements this with a special `0` register and is therefore closer to the ISA.
And with the update of Capstone to mimic LLVM more closely, tracing this was an addition.
Instead of this PR we can ignore the reads of the `0` register in `rz-tracetest` (I think).

Should have pointed all this out in the PR description. @ivg Any comments?

**Review by wargio — COMMENTED** [review]
i wonder if these patches should go to qemu upstream

**Review by wargio — APPROVED** [review]

**Comment by Rot127** [comment]
> i wonder if these patches should go to qemu upstream

I doubt that they see any use in this. Why doing an additional operation of adding `0` to something if you can also just skip it?

**Comment by wargio** [comment]
makes sense.

**Pull request merged**
